"""
Portfolio tracker that monitors signal execution and actual holdings.

This module helps answer:
- Did I actually execute the buy/sell signals?
- What's my current portfolio state?
- How do my actual trades compare to the signals?
"""

import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional

import pandas as pd

from src.portfolio.models import Position, Trade, Signal, PortfolioState


logger = logging.getLogger(__name__)


class PortfolioTracker:
    """
    Track portfolio state and signal execution.

    Simple implementation that:
    1. Stores your actual positions (what you actually bought/sold)
    2. Compares them to generated signals
    3. Calculates performance metrics
    4. Provides feedback to ML models

    Example:
        >>> tracker = PortfolioTracker()
        >>>
        >>> # Record a signal
        >>> tracker.record_signal("RELIANCE", "BUY", 2450.50, datetime.now())
        >>>
        >>> # Record your actual trade
        >>> tracker.record_trade("RELIANCE", "BUY", 2451.00, 100, datetime.now())
        >>>
        >>> # Check execution rate
        >>> tracker.get_execution_rate()
        0.85  # You followed 85% of signals
    """

    def __init__(self, db_path: Optional[str] = None):
        """
        Initialize portfolio tracker.

        Args:
            db_path: Path to DuckDB database. If None, uses in-memory DB.
        """
        self.db_path = db_path or ":memory:"
        self.positions: Dict[str, Position] = {}  # Current holdings
        self.signals: List[Signal] = []  # Generated signals
        self.trades: List[Trade] = []  # Actual executed trades

        self._init_database()

    def _init_database(self):
        """Initialize database tables for tracking."""
        import duckdb

        conn = duckdb.connect(self.db_path)

        # Table for actual positions
        conn.execute("""
            CREATE TABLE IF NOT EXISTS positions (
                symbol VARCHAR PRIMARY KEY,
                quantity INTEGER NOT NULL,
                avg_price DECIMAL(10, 2) NOT NULL,
                current_price DECIMAL(10, 2),
                market_value DECIMAL(12, 2),
                unrealized_pnl DECIMAL(12, 2),
                last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table for generated signals
        conn.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY,
                symbol VARCHAR NOT NULL,
                signal_type VARCHAR NOT NULL,  -- BUY, SELL, HOLD
                signal_price DECIMAL(10, 2) NOT NULL,
                signal_time TIMESTAMP NOT NULL,
                confidence DECIMAL(5, 4),  -- 0.0 to 1.0
                executed BOOLEAN DEFAULT FALSE,
                execution_time TIMESTAMP,
                execution_price DECIMAL(10, 2)
            )
        """)

        # Table for actual trades
        conn.execute("""
            CREATE TABLE IF NOT EXISTS trades (
                id INTEGER PRIMARY KEY,
                symbol VARCHAR NOT NULL,
                trade_type VARCHAR NOT NULL,  -- BUY, SELL
                quantity INTEGER NOT NULL,
                price DECIMAL(10, 2) NOT NULL,
                trade_time TIMESTAMP NOT NULL,
                signal_id INTEGER,  -- Link to signal if followed
                commission DECIMAL(10, 2) DEFAULT 0,
                notes TEXT
            )
        """)

        # Table for feedback to ML
        conn.execute("""
            CREATE TABLE IF NOT EXISTS ml_feedback (
                id INTEGER PRIMARY KEY,
                symbol VARCHAR NOT NULL,
                signal_id INTEGER NOT NULL,
                followed BOOLEAN NOT NULL,
                outcome VARCHAR,  -- PROFIT, LOSS, BREAK_EVEN
                return_pct DECIMAL(10, 4),
                feedback_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        conn.close()
        logger.info(f"Portfolio tracker initialized with database: {self.db_path}")

    def record_signal(
        self,
        symbol: str,
        signal_type: str,
        price: float,
        timestamp: datetime,
        confidence: float = 0.5
    ) -> int:
        """
        Record a signal generated by the ML system.

        Args:
            symbol: Stock symbol (e.g., "RELIANCE")
            signal_type: "BUY", "SELL", or "HOLD"
            price: Price at which signal was generated
            timestamp: When signal was generated
            confidence: Model confidence (0.0 to 1.0)

        Returns:
            Signal ID for tracking
        """
        import duckdb

        conn = duckdb.connect(self.db_path)

        result = conn.execute("""
            INSERT INTO signals (symbol, signal_type, signal_price, signal_time, confidence)
            VALUES (?, ?, ?, ?, ?)
            RETURNING id
        """, [symbol, signal_type, price, timestamp, confidence]).fetchone()

        signal_id = result[0]
        conn.close()

        logger.info(f"Recorded {signal_type} signal for {symbol} at {price} (ID: {signal_id})")
        return signal_id

    def record_trade(
        self,
        symbol: str,
        trade_type: str,
        price: float,
        quantity: int,
        timestamp: datetime,
        signal_id: Optional[int] = None,
        commission: float = 0.0,
        notes: str = ""
    ) -> int:
        """
        Record an actual trade you executed.

        Args:
            symbol: Stock symbol
            trade_type: "BUY" or "SELL"
            price: Actual execution price
            quantity: Number of shares
            timestamp: When trade was executed
            signal_id: Link to signal if you followed one
            commission: Brokerage fees
            notes: Any additional notes

        Returns:
            Trade ID
        """
        import duckdb

        conn = duckdb.connect(self.db_path)

        # Insert trade
        result = conn.execute("""
            INSERT INTO trades (symbol, trade_type, quantity, price, trade_time, signal_id, commission, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
        """, [symbol, trade_type, quantity, price, timestamp, signal_id, commission, notes]).fetchone()

        trade_id = result[0]

        # Update signal as executed if linked
        if signal_id:
            conn.execute("""
                UPDATE signals
                SET executed = TRUE,
                    execution_time = ?,
                    execution_price = ?
                WHERE id = ?
            """, [timestamp, price, signal_id])

        # Update position
        self._update_position(conn, symbol, trade_type, quantity, price)

        conn.close()

        logger.info(f"Recorded {trade_type} trade for {symbol}: {quantity} @ {price} (ID: {trade_id})")
        return trade_id

    def _update_position(self, conn, symbol: str, trade_type: str, quantity: int, price: float):
        """Update position after trade."""

        # Get current position
        result = conn.execute("SELECT quantity, avg_price FROM positions WHERE symbol = ?", [symbol]).fetchone()

        if result:
            current_qty, avg_price = result
        else:
            current_qty, avg_price = 0, 0.0

        # Calculate new position
        if trade_type == "BUY":
            new_qty = current_qty + quantity
            new_avg_price = ((current_qty * avg_price) + (quantity * price)) / new_qty if new_qty > 0 else 0
        else:  # SELL
            new_qty = current_qty - quantity
            new_avg_price = avg_price  # Average price doesn't change on sell

        # Update or insert
        if new_qty > 0:
            conn.execute("""
                INSERT INTO positions (symbol, quantity, avg_price, last_updated)
                VALUES (?, ?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT (symbol) DO UPDATE SET
                    quantity = excluded.quantity,
                    avg_price = excluded.avg_price,
                    last_updated = excluded.last_updated
            """, [symbol, new_qty, new_avg_price])
        elif new_qty == 0:
            # Closed position
            conn.execute("DELETE FROM positions WHERE symbol = ?", [symbol])
        else:
            logger.warning(f"Negative position for {symbol}: {new_qty}")

    def get_current_holdings(self) -> pd.DataFrame:
        """
        Get current portfolio holdings.

        Returns:
            DataFrame with columns: symbol, quantity, avg_price, current_price,
            market_value, unrealized_pnl, pnl_pct
        """
        import duckdb

        conn = duckdb.connect(self.db_path)
        df = conn.execute("SELECT * FROM positions ORDER BY symbol").df()
        conn.close()

        return df

    def get_execution_rate(self, days: int = 30) -> float:
        """
        Calculate what percentage of signals you actually executed.

        Args:
            days: Look back period in days

        Returns:
            Execution rate between 0.0 and 1.0
        """
        import duckdb

        conn = duckdb.connect(self.db_path)

        cutoff = datetime.now() - timedelta(days=days)

        result = conn.execute("""
            SELECT
                COUNT(*) as total_signals,
                SUM(CASE WHEN executed THEN 1 ELSE 0 END) as executed_signals
            FROM signals
            WHERE signal_time >= ?
            AND signal_type IN ('BUY', 'SELL')
        """, [cutoff]).fetchone()

        conn.close()

        total, executed = result
        return executed / total if total > 0 else 0.0

    def get_signal_performance(self) -> pd.DataFrame:
        """
        Analyze performance of signals (both followed and not followed).

        Returns:
            DataFrame with signal performance metrics
        """
        import duckdb

        conn = duckdb.connect(self.db_path)

        df = conn.execute("""
            SELECT
                s.symbol,
                s.signal_type,
                s.signal_price,
                s.signal_time,
                s.confidence,
                s.executed,
                s.execution_price,
                s.execution_time,
                t.quantity,
                t.commission
            FROM signals s
            LEFT JOIN trades t ON s.id = t.signal_id
            ORDER BY s.signal_time DESC
            LIMIT 100
        """).df()

        conn.close()

        return df

    def generate_ml_feedback(self, symbol: str, signal_id: int) -> Dict:
        """
        Generate feedback for ML model based on signal outcome.

        This helps the model learn from your actual results.

        Args:
            symbol: Stock symbol
            signal_id: Signal to evaluate

        Returns:
            Feedback dictionary with outcome and return
        """
        import duckdb

        conn = duckdb.connect(self.db_path)

        # Get signal details
        signal = conn.execute("""
            SELECT signal_type, signal_price, executed, execution_price, execution_time
            FROM signals
            WHERE id = ?
        """, [signal_id]).fetchone()

        if not signal:
            return {"error": "Signal not found"}

        signal_type, signal_price, executed, exec_price, exec_time = signal

        # Get current price to calculate outcome
        # In real implementation, would fetch from market data
        # For now, use a placeholder
        current_price = signal_price * 1.02  # Placeholder: assume 2% move

        # Calculate outcome
        if executed:
            if signal_type == "BUY":
                return_pct = ((current_price - exec_price) / exec_price) * 100
            else:  # SELL
                return_pct = ((exec_price - current_price) / exec_price) * 100

            outcome = "PROFIT" if return_pct > 0 else "LOSS" if return_pct < -0.1 else "BREAK_EVEN"

            # Store feedback
            conn.execute("""
                INSERT INTO ml_feedback (symbol, signal_id, followed, outcome, return_pct)
                VALUES (?, ?, TRUE, ?, ?)
            """, [symbol, signal_id, outcome, return_pct])

            feedback = {
                "symbol": symbol,
                "signal_id": signal_id,
                "followed": True,
                "outcome": outcome,
                "return_pct": return_pct,
                "recommendation": self._get_feedback_recommendation(outcome, return_pct)
            }
        else:
            # Signal not followed - calculate opportunity cost
            if signal_type == "BUY":
                missed_return = ((current_price - signal_price) / signal_price) * 100
            else:
                missed_return = ((signal_price - current_price) / signal_price) * 100

            outcome = "MISSED_PROFIT" if missed_return > 1 else "AVOIDED_LOSS" if missed_return < -1 else "NO_IMPACT"

            conn.execute("""
                INSERT INTO ml_feedback (symbol, signal_id, followed, outcome, return_pct)
                VALUES (?, ?, FALSE, ?, ?)
            """, [symbol, signal_id, outcome, missed_return])

            feedback = {
                "symbol": symbol,
                "signal_id": signal_id,
                "followed": False,
                "outcome": outcome,
                "missed_return_pct": missed_return,
                "recommendation": self._get_feedback_recommendation(outcome, missed_return)
            }

        conn.close()
        return feedback

    def _get_feedback_recommendation(self, outcome: str, return_pct: float) -> str:
        """Generate recommendation based on outcome."""
        if outcome == "PROFIT":
            return "Good trade! Model prediction was accurate."
        elif outcome == "LOSS":
            return "Model may need retraining. Consider reviewing features."
        elif outcome == "MISSED_PROFIT":
            return "Consider following high-confidence signals more consistently."
        elif outcome == "AVOIDED_LOSS":
            return "Good decision to skip this signal."
        else:
            return "Neutral outcome. Continue monitoring."

    def get_portfolio_summary(self) -> Dict:
        """
        Get comprehensive portfolio summary.

        Returns:
            Dictionary with portfolio metrics
        """
        import duckdb

        conn = duckdb.connect(self.db_path)

        # Current holdings
        holdings = conn.execute("SELECT COUNT(*), SUM(market_value) FROM positions").fetchone()
        num_positions, total_value = holdings if holdings[0] else (0, 0)

        # Recent signals
        signals_30d = conn.execute("""
            SELECT COUNT(*) FROM signals
            WHERE signal_time >= CURRENT_TIMESTAMP - INTERVAL '30 days'
        """).fetchone()[0]

        # Recent trades
        trades_30d = conn.execute("""
            SELECT COUNT(*) FROM trades
            WHERE trade_time >= CURRENT_TIMESTAMP - INTERVAL '30 days'
        """).fetchone()[0]

        # Execution rate
        exec_rate = self.get_execution_rate(days=30)

        conn.close()

        return {
            "num_positions": num_positions,
            "total_market_value": total_value,
            "signals_30d": signals_30d,
            "trades_30d": trades_30d,
            "execution_rate": exec_rate,
            "timestamp": datetime.now()
        }
